name: CI

# Triggers the workflow on push or pull request events for any branch that has
# this file
on: [push, pull_request]

# This workflow has only one job, since the three jobs are already combined into
# the `yarn ci` command
jobs:
  ci:
    name: Test and build on node ${{ matrix.node_version }}
    # Run the job on an instance of Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run on node 14
        node_version: ['14.x']
    steps:
      # `git clone` the repo
      - name: Check out repo
        uses: actions/checkout@v1
      # Setup the specified version of node
      - name: Setup node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      # Install dependencies and run the `yarn ci` command
      - name: Test and build
        run: |
          yarn
          yarn ci
        env:
          # Variables needed for the tests to run
          MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
          MICROSOFT_CLIENT_SECRET: ${{ secrets.MICROSOFT_CLIENT_SECRET }}
          MICROSOFT_REDIRECT_URI: ${{ secrets.MICROSOFT_REDIRECT_URI }}
          MICROSOFT_REFRESH_TOKEN: ${{ secrets.MICROSOFT_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets.GOOGLE_REDIRECT_URI }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      # Save the built executables
      - name: Uploading alpine executable
        uses: actions/upload-artifact@v2
        with:
          name: files-api-server-alpine
          path: execs/files-api-server-alpine
      - name: Uploading linux executable
        uses: actions/upload-artifact@v2
        with:
          name: files-api-server-linux
          path: execs/files-api-server-linux
      - name: Uploading macos executable
        uses: actions/upload-artifact@v2
        with:
          name: files-api-server-macos
          path: execs/files-api-server-macos
      - name: Uploading windows executable
        uses: actions/upload-artifact@v2
        with:
          name: files-api-server-win.exe
          path: execs/files-api-server-win.exe
